// Use a CMS-friendly shape. Each item can include `class` (raw tailwind classes) or `color` token.
export const topbarLinks = [
  {
    label: 'Admission Open',
    href: '/merit',
    target: '_self',
    hoverText: 'Apply Now',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: true,
    class: '',
    order: 0,
    isVisible: true,
  },
  {
    label: 'Results',
    href: '/merit',
    target: '_self',
    hoverText: 'View Results',
    showOnDesktop: true,
    showOnMobile: false,
    isAlert: true,
    class: ' ',
    order: 1,
    isVisible: false,
  },
 
  {
    label: 'Alumni',
    href: '/alumni',
    target: '_self',
    hoverText: 'Alumni',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 2,
    isVisible: true,
  },
  {
    label: 'UW FM Radio',
    href: 'https://radio.uow.edu.pk',
    target: '_blank',
    hoverText: 'UW FM Radio',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 3,
    isVisible: true,
  },
  {
    label: 'Careers',
    href: 'https://career.uow.edu.pk',
    target: '_blank',
    hoverText: 'Apply',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 4,
    isVisible: true,
  },
   {
    label: 'Avicenna CMS',
    href: '/avicenna',
    target: '_self',
    hoverText: 'Avicenna CMS',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 4,
    isVisible: true,
  },
  {
    label: 'Download',
    href: '/',
    target: '_self',
    hoverText: 'Get Files',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 5,
    isVisible: true,
  },
  {
    label: 'Events',
    href: '/',
    target: '_self',
    hoverText: 'See All',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 6,
    isVisible: true,
  },
  {
    label: 'Search',
    href: '/',
    target: '_self',
    hoverText: 'Find',
    showOnDesktop: true,
    showOnMobile: true,
    isAlert: false,
    class: '',
    order: 7,
    isVisible: true,
    ariaLabel: 'Search',
  },
];

export default topbarLinks;
